server:
  port: 8501

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.211.55.4:3306/db_spzx?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
  data:
    redis:
      host: 10.211.55.4
      port: 6379
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

mybatis:
  mapper-locations: classpath:/mapper/*/*.xml
  config-location: classpath:/mybatis-config.xml

spzx:
  auth:
    noAuthUrls:
      - /admin/system/index/login
      - /admin/system/index/generateValidateCode

  minio:
    endpointUrl: http://10.211.55.4:9001
    accessKey: admin
    secreKey: admin123456
    bucketName: spzx-bucket
